services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    #ports:
    #  - "8080:80"
    networks:
      - proxy-net
    restart: unless-stopped
networks:
  proxy-net:
    external: true
