services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80'       # Public HTTP Port
      - '81:81'       # Admin Web Interface
      - '443:443'     # Public HTTPS Port
    networks:
      - proxy-net
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  proxy-net:
    external: true
